/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZI_021ObjectPageObjectPage journey");

        opaTest("Navigate to ZI_021ObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheZI_021List.onFilterBar().iExecuteSearch();

            Then.onTheZI_021List.onTable().iCheckRows();
            When.onTheZI_021List.onTable().iPressRow(0);

            Then.onTheZI_021ObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZI_021ObjectPage.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheZI_021ObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "product_id" });
            Then.onTheZI_021ObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "product_name" });
            Then.onTheZI_021ObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "price" });
            Then.onTheZI_021ObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "currancy" });
            Then.onTheZI_021ObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "created_by" });
            Then.onTheZI_021ObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "created_at" });
            Then.onTheZI_021ObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "last_changed_by" });
            Then.onTheZI_021ObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "last_change_at" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});